### ISSUE TITLE
Idea for styling?

### ISSUE THREAD

**Issue by Kopite4Ever** [jeffreykemp/jk64-plugin-passwordstrength#1]
Hi Jeff this looks a really useful plug-in thanks for posting it.

I was playing with something called strength.js a few months ago https://www.jquerycards.com/forms/inputs/strength-js/ (none APEX related)

Maybe its something you can incorporate styling wise to your input box instead of the weak/poor/good/ etc notification text outside of the input box.  I think the logic for passwords in your plug-in is much better.

Just a thought other than that its working great !

**Comment by jeffreykemp** [comment]
That plugin certainly looks pretty. I'm not that strong with doing that sort of fancy styling but if you want to have a go, my plugin is open source and I'd love to see what you can do with it.

**Comment by Kopite4Ever** [comment]
Great I will fork it off and find some time to have a go :)

Cheers
